[config.wallpaper]
command = "awww img {{ image }}"
set = true

[templates.eww]
input_path = '~/.config/matugen/templates/colors-eww.scss'
output_path = '~/.config/eww/colors.scss'
post_hook = 'eww reload'
