// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.shield.optoutstudies.enabled", true);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
user_pref("browser.discovery.enabled", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.customIcon.enabled", null);
user_pref("browser.shell.customIcon.id", null);
user_pref("browser.shell.customIcon.perUserStartMenuShortcutCreated", null);
user_pref("browser.backup.enabled_on.profiles", "[]");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "575e9df3-4c7f-4ab7-abe5-03ba3f2e9bba");
user_pref("datareporting.healthreport.uploadEnabled", true);
user_pref("datareporting.policy.currentPolicyVersion", 2);
user_pref("datareporting.policy.dataSubmissionEnabled", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyBypassNotification", false);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1789724549564");
user_pref("datareporting.policy.minimumPolicyVersion", 1);
user_pref("datareporting.policy.minimumPolicyVersion.channel-beta", 2);
user_pref("datareporting.usage.uploadEnabled", true);
user_pref("termsofuse.acceptedDate", "0");
user_pref("termsofuse.firstAcceptedDate", "0");
user_pref("termsofuse.acceptedVersion", 0);
user_pref("termsofuse.bypassNotification", false);
user_pref("termsofuse.currentVersion", 4);
user_pref("termsofuse.minimumVersion", 4);
user_pref("toolkit.telemetry.cachedProfileGroupID", "9d1abeb0-1de4-478b-ad3e-dd2ffecf024d");
user_pref("browser.profiles.enabled", true);
user_pref("browser.profiles.created", true);
user_pref("toolkit.profiles.storeID", "c006f8c8");
